### ISSUE TITLE
启动后有许多错误日志,杀死App后信鸽后台群发收不到,按deviceToken能收到

### ISSUE THREAD

**Issue by apm29** [v7lin/fake_push#12]
## 日志信息
```
E/XgStat  (15996): 
E/XgStat  (15996): java.net.SocketTimeoutException: Read timed out
E/XgStat  (15996): 	at java.net.SocketInputStream.socketRead0(Native Method)
E/XgStat  (15996): 	at java.net.SocketInputStream.read(SocketInputStream.java:151)
E/XgStat  (15996): 	at java.net.SocketInputStream.read(SocketInputStream.java:120)
E/XgStat  (15996): 	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:108)
E/XgStat  (15996): 	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:196)
E/XgStat  (15996): 	at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:88)
E/XgStat  (15996): 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:179)
E/XgStat  (15996): 	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:185)
E/XgStat  (15996): 	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:240)
E/XgStat  (15996): 	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:264)
E/XgStat  (15996): 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:284)
E/XgStat  (15996): 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:126)
E/XgStat  (15996): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:442)
E/XgStat  (15996): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:596)
E/XgStat  (15996): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:517)
E/XgStat  (15996): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:495)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.f.a(ProGuard:256)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.f.b(ProGuard:371)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.f.a(ProGuard:383)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.g.a(ProGuard:694)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.g.a(ProGuard:337)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.g.b(ProGuard:370)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.g$14.run(ProGuard:610)
E/XgStat  (15996): 	at android.os.Handler.handleCallback(Handler.java:761)
E/XgStat  (15996): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/XgStat  (15996): 	at android.os.Looper.loop(Looper.java:156)
E/XgStat  (15996): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/XgStat  (15996): 
E/XgStat  (15996): java.net.SocketTimeoutException: Read timed out
E/XgStat  (15996): 	at java.net.SocketInputStream.socketRead0(Native Method)
E/XgStat  (15996): 	at java.net.SocketInputStream.read(SocketInputStream.java:151)
E/XgStat  (15996): 	at java.net.SocketInputStream.read(SocketInputStream.java:120)
E/XgStat  (15996): 	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:108)
E/XgStat  (15996): 	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:196)
E/XgStat  (15996): 	at org.apache.http.impl.conn.DefaultResponseParser.parseHead(DefaultResponseParser.java:88)
E/XgStat  (15996): 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:179)
E/XgStat  (15996): 	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:185)
E/XgStat  (15996): 	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:240)
E/XgStat  (15996): 	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:264)
E/XgStat  (15996): 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:284)
E/XgStat  (15996): 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:126)
E/XgStat  (15996): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:442)
E/XgStat  (15996): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:596)
E/XgStat  (15996): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:517)
E/XgStat  (15996): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:495)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.f.a(ProGuard:256)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.f.b(ProGuard:371)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.g.e(ProGuard:770)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.g.b(ProGuard:978)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.g$15.run(ProGuard:661)
E/XgStat  (15996): 	at android.os.Handler.handleCallback(Handler.java:761)
E/XgStat  (15996): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/XgStat  (15996): 	at android.os.Looper.loop(Looper.java:156)
E/XgStat  (15996): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/XgStat  (15996): 
E/XgStat  (15996): java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
E/XgStat  (15996): 	at android.app.SharedPreferencesImpl.getInt(SharedPreferencesImpl.java:260)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.g.d(ProGuard:752)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.g$3.b(ProGuard:779)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.f.a(ProGuard:345)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.f.b(ProGuard:371)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.g.e(ProGuard:770)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.g.b(ProGuard:978)
E/XgStat  (15996): 	at com.tencent.android.tpush.stat.g$15.run(ProGuard:661)
E/XgStat  (15996): 	at android.os.Handler.handleCallback(Handler.java:761)
E/XgStat  (15996): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/XgStat  (15996): 	at android.os.Looper.loop(Looper.java:156)
E/XgStat  (15996): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

## Flutter doctor 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.8.1-pre.2, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (3 available)

• No issues found!
```

*  启动后有许多错误日志,杀死App后信鸽后台群发收不到,按deviceToken能收到,点击通知一个回调也没走
* 测试机是两个华为的平板Android7.0 型号BTV-DL09(暂时没接入其他厂商渠道)

**Comment by apm29** [comment]
之后又测试了小米的推送,小米后台发都能收到,信鸽后台发收不到....

**Comment by v7lin** [comment]
好的

**Comment by v7lin** [comment]
小米测试正常。华为正在测试。

**Comment by v7lin** [comment]
至于日志问题，这是信鸽SDK自身生产的。不必理会

**Comment by chenxianqi** [comment]
你的问题貌似和我的差不多 #11

**Comment by apm29** [comment]
现在打release 包 ,找不到class...
```
2019-07-12 15:47:44.712 10377-10377/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.spark.zj.is.school, PID: 10377
    java.lang.RuntimeException: Unable to get provider com.tencent.android.tpush.SettingsContentProvider: java.lang.ClassNotFoundException: Didn't find class "com.tencent.android.tpush.SettingsContentProvider" on path: DexPathList[[zip file "/data/app/com.spark.zj.is.school-gibWUuMApzUNwdXSt0ZU3A==/base.apk"],nativeLibraryDirectories=[/data/app/com.spark.zj.is.school-gibWUuMApzUNwdXSt0ZU3A==/lib/arm, /data/app/com.spark.zj.is.school-gibWUuMApzUNwdXSt0ZU3A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:7215)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6699)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6600)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.android.tpush.SettingsContentProvider" on path: DexPathList[[zip file "/data/app/com.spark.zj.is.school-gibWUuMApzUNwdXSt0ZU3A==/base.apk"],nativeLibraryDirectories=[/data/app/com.spark.zj.is.school-gibWUuMApzUNwdXSt0ZU3A==/lib/arm, /data/app/com.spark.zj.is.school-gibWUuMApzUNwdXSt0ZU3A==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7200)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6699) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6600) 
        at android.app.ActivityThread.-wrap2(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7529) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
```

**Comment by v7lin** [comment]
Android遇到这类问题，走走基本流程
1. 想想确认混淆没写错
2. multiDexEnabled true
3. flutter clean
4. 重启
5. 请教，并贴上相关混淆内容

**Comment by v7lin** [comment]
clean能解决百分八十的问题
